services:
  postgres:
    container_name: postgres
    image: postgres
    shm_size: "2gb"
    restart: always
    expose:
      - "5432"
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "./docker/data/postgres/data/:/var/lib/postgresql/data"

  nginx:
    container_name: botter_api__nginx
    image: nginx
    restart: always
    network_mode: host
    volumes:
      - "./docker/nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro"

  redis:
    container_name: botter_api__redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
